[package]
name = "midgard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
robotics_lib = { path="../Robotic-Lib" }
noise = { version = "0.8.2" }
bevy = { version = "0.12", default_features = false }
bevy_pixels = "*"