[registries]
kellnr = { index = "sparse+https://advancedprogramming.disi.unitn.it/api/v1/crates/", token = "secret_token" }

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]